name: CI Pipeline
on:
  push:
    branches: [ master, staging ]
  pull_request:
    branches: [ master, staging ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run linting tests
        run: npm test
        
      - name: Validate HTML files
        run: npm run lint:html
        
      - name: Validate CSS files  
        run: npm run lint:css
        
      - name: Validate JavaScript files
        run: npm run lint:js
