name: cloudjp CI
on:
  push:
    branches: [ master, staging ]
  pull_request:
    branches: [ master, staging ]

jobs:
  cloudjp-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: package.jsonの存在確認
        id: check-package
        run: |
          if [ -f "package.json" ]; then
            echo "has-package=true" >> $GITHUB_OUTPUT
          else
            echo "has-package=false" >> $GITHUB_OUTPUT
          fi
          
      - name: 基本バリデーション (依存関係なし)
        if: steps.check-package.outputs.has-package == 'false'
        run: |
          echo "⚡ package.jsonなし - 基本バリデーション実行中"
          find . -name "*.html" -exec echo "発見: {}" \;
          echo "✅ 静的ファイル検証完了"
          
      - name: 最小バリデーション (依存関係あり)
        if: steps.check-package.outputs.has-package == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: 最小依存関係のインストール
        if: steps.check-package.outputs.has-package == 'true'
        run: npm ci
        
      - name: HTMLバリデーション実行
        if: steps.check-package.outputs.has-package == 'true'
        run: npm test